### PR TITLE
Support extra arguments to venv creation

### PR DESCRIPTION
**Pull request by simaoafonso-pwt**
This is configured just like other variables.

### CODE REVIEW

**Comment by sio** [comment]
Thank you for coming up with this feature!

Could you explain where it may be of use? Some example use case which was not supported by Makefile.venv before but would work now?

How could we test this?

**Comment by simaoafonso-pwt** [comment]
On my part, I'm trying to port a project to ARM. There's a `numpy` dependency, which means C extensions and all that hassle, there are no public wheels for `numpy` on ARM.

Instead of compiling `numpy` by myself, I can just install `python3-numpy`, and create the `venv` with `--system-site-packages`, which picks it up from the system packages.

https://docs.python.org/3/library/venv.html

The other interesting options (from perusing the help docs) are:
- `--clear` will blow away the entire venv folder
- `--prompt PROMPT` will let you change the prompt name. This could be a cosmetic enhancement, to stop the prompt to be called `.venv`.

---

I'm not sure how to test this. This is only useful on very small number of special cases.

**Comment by simaoafonso-pwt** [comment]
> This could be a cosmetic enhancement, to stop the prompt to be called .venv.

https://bugs.python.org/issue35328

This needs to wait for Python 3.9, at least.

**Comment by sio** [comment]
Yeah, I was afraid you're after `--system-site-packages`... I strongly feel that using it is an anti-pattern and I would like not to endorse it via Makefile.venv. Of course if you have good arguments in favor of `--system-site-packages`, I'm open to discussion.

May be we can find a workaround for your use case that does not involve modifying Makefile.venv for everyone?

Here are the options I see so far:

---

#### a) Build the wheel for numpy once and install it automatically by injecting a dependency recipe:

```Makefile
## Put this into your Makefile after `include Makefile.venv`

# Add wheel as dependency for venv initialization recipe
$(VENV)/$(MARKER): | wheel

# Actual wheel recipe
.PHONY: wheel
wheel: | $(VENV)
	# Steps to fetch and install your wheel
```

This way you're actually in control of what numpy build is in use instead of assuming that the system wide is good enough. Also this Makefile will work on other systems without numpy installed.

#### a1) Same as a) but do not install the wheel, only place it into pip cache

#### b) Overwrite the recipe for creating venv

```Makefile
## Put this into your Makefile after `include Makefile.venv`

$(VENV):
	$(PY) -m venv --system-site-packages $(VENVDIR)
	$(VENV)/python -m pip install --upgrade pip setuptools wheel
```

Second recipe definition will be used instead of the one provided by Makefile.venv ([docs](https://www.gnu.org/software/make/manual/html_node/Multiple-Rules.html#:~:text=4.11%20Multiple%20Rules%20for%20One%20Target&text=There%20can%20only%20be%20one,no%20error%20message%20is%20printed.) explain this behavior). You get to have `--system-site-packages` with all their drawbacks but that does not affect other Makefile.venv users.

#### c) Build the wheel and publish it via custom package index

---

How about these?

**Comment by simaoafonso-pwt** [comment]
> Yeah, I was afraid you're after --system-site-packages... I strongly feel that using it is an anti-pattern and I would like not to endorse it via Makefile.venv.

Yes, it's a complete hail mary, not something I would use in normal circumstances.

---

I think `b)` works for me. `c)` would be ideal, but that's not easy for now.
This is only on a specific case anyway, just trying to document things for future me when this comes up in the future.

Thanks for your help, I'm closing this.

**Pull request closed without merging**
